name: GpoTNT
favicon: null
layout_spectrum: 0.07962459861300886
typography_spectrum: 0.35587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e46c0b'
    - '#000000'
    - '#c6c6c6'
    - '#005663'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
